repository:
  name: "json-api-parser"
  description: "Utilities for parsing and flattening responses from a JSON:API standard web API "
  private: false
  has_projects: false
  has_wiki: false

  default_branch: main
  delete_branch_on_merge: false

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        require_code_owner_reviews: true
        dismiss_stale_reviews: true
        required_approving_review_count: 1

      required_status_checks:
        strict: true
        contexts: []